import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"

const tap = "github.com/synthetic-sciences/homebrew-tap.git"
const quote = (value: string) => `'${value.replaceAll("'", "'\\''")}'`

export function homebrewFormula(input: {
  version: string
  sha256: { darwinArm64: string; darwinX64: string; linuxArm64: string; linuxX64: string }
}) {
  if (!/^\d+\.\d+\.\d+$/.test(input.version)) throw new Error("Homebrew requires a stable release version")
  for (const value of Object.values(input.sha256))
    if (!/^[a-f0-9]{64}$/.test(value)) throw new Error("Homebrew requires verified SHA-256 digests")
  return [
    "# typed: false",
    "# frozen_string_literal: true",
    "",
    "# Generated by OpenScience release tooling.",
    "class Openscience < Formula",
    '  desc "AI research agent built for the terminal"',
    '  homepage "https://github.com/synthetic-sciences/openscience"',
    `  version "${input.version}"`,
    '  license "Apache-2.0"',
    "",
    '  depends_on "ripgrep"',
    ...(["macos", "linux"] as const).flatMap((platform) => [
      "",
      `  on_${platform} do`,
      ...(["intel", "arm"] as const).flatMap((arch) => {
        const target = `${platform === "macos" ? "darwin" : "linux"}-${arch === "intel" ? "x64" : "arm64"}`
        const digest =
          platform === "macos"
            ? arch === "intel"
              ? input.sha256.darwinX64
              : input.sha256.darwinArm64
            : arch === "intel"
              ? input.sha256.linuxX64
              : input.sha256.linuxArm64
        return [
          `    on_${arch} do`,
          `      url "https://github.com/synthetic-sciences/openscience/releases/download/v${input.version}/openscience-${target}.${platform === "macos" ? "zip" : "tar.gz"}"`,
          `      sha256 "${digest}"`,
          "    end",
        ]
      }),
      "  end",
    ]),
    "",
    "  def install",
    '    bin.install "openscience"',
    "  end",
    "",
    "  test do",
    '    assert_match version.to_s, shell_output("#{bin}/openscience --version")',
    "  end",
    "end",
    "",
  ].join("\n")
}

/** Credentials live only in an owned, temporary directory or child environment.
 * GitHub's authenticated HTTPS metadata supplies host keys; SSH cannot TOFU. */
export async function withHomebrewAuth<T>(
  credentials: { sshKey?: string; token?: string },
  run: (auth: { directory: string; url: string; env: NodeJS.ProcessEnv }) => Promise<T>,
  request: (url: string, init: RequestInit) => Promise<Response> = fetch,
) {
  if (!credentials.sshKey?.trim() && !credentials.token?.trim()) throw new Error("Homebrew credentials are missing")
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), "openscience-homebrew-"))
  try {
    const env: NodeJS.ProcessEnv = {
      ...Object.fromEntries(
        ["PATH", "HOME", "TMPDIR", "TMP", "TEMP", "SystemRoot", "SYSTEMROOT", "COMSPEC", "PATHEXT"]
          .filter((name) => process.env[name] !== undefined)
          .map((name) => [name, process.env[name]]),
      ),
      GIT_TERMINAL_PROMPT: "0",
      GIT_CONFIG_NOSYSTEM: "1",
      GIT_CONFIG_GLOBAL: os.devNull,
    }
    if (credentials.sshKey?.trim()) {
      const response = await request("https://api.github.com/meta", {
        headers: { Accept: "application/vnd.github+json", "User-Agent": "OpenScience-release" },
        redirect: "error",
        signal: AbortSignal.timeout(10_000),
      })
      if (!response.ok) throw new Error("GitHub host keys unavailable")
      const metadata: unknown = await response.json()
      const keys = metadata && typeof metadata === "object" && "ssh_keys" in metadata ? metadata.ssh_keys : undefined
      if (
        !Array.isArray(keys) ||
        !keys.length ||
        !keys.every(
          (key) =>
            typeof key === "string" && /^(ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp256) [A-Za-z0-9+/]+={0,2}$/.test(key),
        )
      )
        throw new Error("GitHub host keys are invalid")
      const key = path.join(directory, "identity")
      const known = path.join(directory, "known_hosts")
      await fs.writeFile(key, credentials.sshKey.trim() + "\n", { mode: 0o600, flag: "wx" })
      await fs.writeFile(known, keys.map((value) => `github.com ${value}\n`).join(""), { mode: 0o600, flag: "wx" })
      env.GIT_SSH_COMMAND = `ssh -F ${quote(os.devNull)} -i ${quote(key)} -o IdentitiesOnly=yes -o IdentityAgent=none -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=${quote(known)} -o GlobalKnownHostsFile=${quote(os.devNull)}`
      return await run({ directory, url: `git@${tap.replace("github.com/", "github.com:")}`, env })
    }
    const askpass = path.join(directory, "askpass")
    await fs.writeFile(
      askpass,
      '#!/bin/sh\ncase "$1" in\n  *Username*) printf "%s\\n" "x-access-token" ;;\n  *Password*) printf "%s\\n" "$OPENSCIENCE_HOMEBREW_TOKEN" ;;\n  *) exit 1 ;;\nesac\n',
      { mode: 0o700, flag: "wx" },
    )
    env.GIT_ASKPASS = askpass
    env.OPENSCIENCE_HOMEBREW_TOKEN = credentials.token
    return await run({ directory, url: `https://${tap}`, env })
  } catch {
    // Never relay child/transport exceptions that may include credentials.
    throw new Error("Homebrew tap update failed; authentication and Git output were withheld")
  } finally {
    await fs.rm(directory, { recursive: true, force: true })
  }
}

async function git(args: string[], cwd: string, env: NodeJS.ProcessEnv) {
  const proc = Bun.spawn(["git", ...args], { cwd, env, stdin: "ignore", stdout: "pipe", stderr: "ignore" })
  const timeout = setTimeout(() => proc.kill(), 120_000)
  try {
    const [code, output] = await Promise.all([proc.exited, new Response(proc.stdout).text()])
    return { code, output }
  } finally {
    clearTimeout(timeout)
  }
}

/** Also used against a local bare repository by the offline release tests. */
export async function updateHomebrewCheckout(input: {
  directory: string
  url: string
  env: NodeJS.ProcessEnv
  formula: string
  version: string
}) {
  if ((await git(["clone", "--depth=1", "--", input.url, "tap"], input.directory, input.env)).code !== 0)
    throw new Error("Homebrew git clone failed")
  const cwd = path.join(input.directory, "tap")
  await fs.writeFile(path.join(cwd, "openscience.rb"), input.formula)
  if ((await git(["add", "--", "openscience.rb"], cwd, input.env)).code !== 0)
    throw new Error("Homebrew git add failed")
  const revision = async (status: "updated" | "unchanged") => {
    const head = await git(["rev-parse", "HEAD"], cwd, input.env)
    if (head.code !== 0 || !/^[a-f0-9]{40}\s*$/.test(head.output)) throw new Error("Homebrew revision is unavailable")
    return { status, commit: head.output.trim() }
  }
  const diff = (await git(["diff", "--cached", "--quiet", "--exit-code"], cwd, input.env)).code
  if (diff === 0) return revision("unchanged")
  if (diff !== 1) throw new Error("Homebrew git diff failed")
  if (
    (
      await git(
        [
          "-c",
          "user.name=github-actions[bot]",
          "-c",
          "user.email=41898282+github-actions[bot]@users.noreply.github.com",
          "commit",
          "-m",
          `Update to v${input.version}`,
        ],
        cwd,
        input.env,
      )
    ).code !== 0
  )
    throw new Error("Homebrew git commit failed")
  if ((await git(["push", "origin", "HEAD"], cwd, input.env)).code !== 0) throw new Error("Homebrew git push failed")
  return revision("updated")
}

export async function updateHomebrewTap(input: { formula: string; version: string; sshKey?: string; token?: string }) {
  return withHomebrewAuth(input, (auth) =>
    updateHomebrewCheckout({ ...auth, formula: input.formula, version: input.version }),
  )
}
